# Generated by Django 6.0.5 on 2026-05-15 08:23

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vibe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='vibelike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vibe',
            name='snippet_end',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vibe',
            name='snippet_start',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vibe',
            name='track_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='vibe',
            constraint=models.CheckConstraint(condition=models.Q(('snippet_end__gt', models.F('snippet_start')), ('snippet_start__isnull', True), ('snippet_end__isnull', True), _connector='OR'), name='snippet_end_greater_than_start_if_present'),
        ),
        migrations.AddConstraint(
            model_name='vibelike',
            constraint=models.UniqueConstraint(fields=('user', 'vibe'), name='unique_user_vibe_like'),
        ),
    ]
